# Generated by Django 5.0.3 on 2024-03-28 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answer_test'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='is_correct'),
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(db_index=True, default=False, verbose_name='is_done')),
                ('result', models.IntegerField(default=-1, verbose_name='result')),
                ('amount_questions', models.SmallIntegerField(default=0, verbose_name='amount_questions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentresults', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentresults', to='questions.test', verbose_name='test')),
            ],
            options={
                'verbose_name': 'studentresult',
                'verbose_name_plural': 'studentresults',
            },
        ),
    ]
